apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ganesh-pod"
  annotations:
    "humanitec.com/orgId": "htc-demo-24"
    "humanitec.com/appId": "ganesh-pod"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
